### ISSUE TITLE
Dropbox links no longer working

### ISSUE THREAD

**Issue by lahavlipson** [HajimeTaira/InLoc_dataset#10]
Hello,

It seems the dropbox links in extract_db_all_mirror.sh are no longer working. They all give **Error (400)**

e.g.

https://www.dropbox.com/s/i19j9mnrrvbpywp/DUC1.tar.bz2?dl=1

**Comment by Xanthorapedia** [comment]
Any updates? It would be great if anyone can at least share the alignments. I was able to get everything else from https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/InLoc/.

**Comment by tsattler** [comment]
I think here is a copy of the dataset: https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/InLoc/ 
Not sure if it contains all data.

**Comment by Xanthorapedia** [comment]
> I think here is a copy of the dataset: https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/InLoc/ Not sure if it contains all data.

Thanks for the reply. It contains all but the [database/alignments](https://github.com/HajimeTaira/InLoc_dataset#structure). However, I was able to download them from https://cvpr17.wijmans.xyz/data/ referred to in the reference section below.

**Comment by Parskatt** [comment]
DUC1: https://www.dropbox.com/s/v4fh8qo5ec03av1/DUC1_alignment.zip?dl=0
DUC2: https://www.dropbox.com/s/vzzvs8z7ytjt33k/DUC2_alignment.zip?dl=0

**Comment by haoningc** [comment]
Why is there only one transformation matrix for alignment instead of one for each graph?
